export enum Queue {
  SERVER_API = 'SERVER_API',
  DISCORD_BOT = 'DISCORD_BOT',
  DISCORD_ANALYZER = 'DISCORD_ANALYZER',
  DISCORD_HIVEMIND_ADAPTER = 'DISCORD_HIVEMIND_ADAPTER',
  TWITTER_BOT = 'TWITTER_BOT',
  HIVEMIND = 'HIVEMIND',
}
