import { IChoreography } from '../interfaces/choreography.interface';
import {
  DISCORD_FETCH_MEMBERS_TRANSACTIONS,
  DISCORD_SCHEDULED_JOB_TRANSACTIONS,
  DISCORD_UPDATE_CHANNELS_TRANSACTIONS,
  TWITTER_REFRESH_TRANSACTIONS,
  ANNOUNCEMENT_SEND_MESSAGE_TO_USER_TRANSACTIONS,
  ANNOUNCEMENT_SEND_MESSAGE_TO_CHANNEL_TRANSACTIONS
} from './transaction';

/* define the DISCORD_UPDATE_CHANNELS choreography  */
const DISCORD_UPDATE_CHANNELS: IChoreography = {
  name: 'DISCORD_UPDATE_CHANNELS',
  transactions: DISCORD_UPDATE_CHANNELS_TRANSACTIONS,
};

/* define the DISCORD_SCHEDULED_JOB choreography  */
const DISCORD_SCHEDULED_JOB: IChoreography = {
  name: 'DISCORD_SCHEDULED_JOB',
  transactions: DISCORD_SCHEDULED_JOB_TRANSACTIONS,
};

const DISCORD_FETCH_MEMBERS: IChoreography = {
  name: 'DISCORD_FETCH_MEMBERS',
  transactions: DISCORD_FETCH_MEMBERS_TRANSACTIONS,
};

const TWITTER_REFRESH: IChoreography = {
  name: 'TWITTER_REFRESH',
  transactions: TWITTER_REFRESH_TRANSACTIONS
}

const ANNOUNCEMENT_SEND_MESSAGE_TO_USER: IChoreography = {
  name: 'ANNOUNCEMENT_SEND_MESSAGE_TO_USER',
  transactions: ANNOUNCEMENT_SEND_MESSAGE_TO_USER_TRANSACTIONS
}

const ANNOUNCEMENT_SEND_MESSAGE_TO_CHANNEL: IChoreography = {
  name: 'ANNOUNCEMENT_SEND_MESSAGE_TO_CHANNEL',
  transactions: ANNOUNCEMENT_SEND_MESSAGE_TO_CHANNEL_TRANSACTIONS
}

/* all available Choreographies, will grow overtime */
export const ChoreographyDict = {
  DISCORD_UPDATE_CHANNELS,
  DISCORD_SCHEDULED_JOB,
  DISCORD_FETCH_MEMBERS,

  // Twitter
  TWITTER_REFRESH,

  // Announcement
  ANNOUNCEMENT_SEND_MESSAGE_TO_USER,
  ANNOUNCEMENT_SEND_MESSAGE_TO_CHANNEL

} as const;
